// AUTO-GENERATED by scripts/generate-article-registry.mjs
// Do not edit directly; run npm run generate:articles-registry
export const articleRegistry: Record<string, () => Promise<{ default: React.FC }>> = {
  "agile-scrum": () => import("./agile-scrum"),
  "devops-philosophy": () => import("./devops-philosophy"),
  "lean-startup": () => import("./lean-startup")
};
