// AUTO-GENERATED by scripts/generate-article-registry.mjs
// Do not edit directly; run npm run generate:articles-registry
export const articleRegistry: Record<string, () => Promise<{ default: React.FC }>> = {
  "agile-scrum": () => import("./agile-scrum"),
  "artifact-management": () => import("./artifact-management"),
  "build-automation": () => import("./build-automation"),
  "capacity-planning": () => import("./capacity-planning"),
  "change-management": () => import("./change-management"),
  "code-editors-vs-ides": () => import("./code-editors-vs-ides"),
  "code-reviews": () => import("./code-reviews"),
  "dependency-management": () => import("./dependency-management"),
  "developer-productivity-tools": () => import("./developer-productivity-tools"),
  "devops-philosophy": () => import("./devops-philosophy"),
  "documentation-standards": () => import("./documentation-standards"),
  "extension-ecosystems": () => import("./extension-ecosystems"),
  "feature-flags": () => import("./feature-flags"),
  "integrated-development-environments": () => import("./integrated-development-environments"),
  "lean-startup": () => import("./lean-startup"),
  "mob-programming": () => import("./mob-programming"),
  "package-managers": () => import("./package-managers"),
  "pair-programming": () => import("./pair-programming"),
  "risk-assessment": () => import("./risk-assessment"),
  "rollback-procedures": () => import("./rollback-procedures"),
  "sprint-planning": () => import("./sprint-planning"),
  "technical-debt-management": () => import("./technical-debt-management"),
  "version-control-strategies": () => import("./version-control-strategies"),
  "waterfall": () => import("./waterfall")
};
